apiVersion: v1
kind: Secret
metadata:
  name: backend-env
type: Opaque
stringData:
  PORT: "5000"
  MONGO_URI: "mongodb://mongo:27017/recipe-planner"
  JWT_SECRET: "your_jwt_secret"
  CORS_ORIGIN: "*"
