apiVersion: v1
kind: Service
metadata:
  name: recipe-planner-frontend-service
  namespace: recipe-planner
spec:
  type: NodePort
  selector:
    app: recipe-planner-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
