apiVersion: v1
kind: Service
metadata:
  name: recipe-planner-backend-service
  namespace: food-planner
spec:
  type: NodePort
  selector:
    app: recipe-planner-backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
