name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          eval $(minikube docker-env)
        shell: bash

      # Build and push backend image
      - name: Build Backend Docker image
        run: |
          cd app/backend
          docker build -t samiscd/recipe-planner-mern-backend:latest .

      - name: Build Frontend Docker image
        run: |
          cd app/frontend
          docker build -t samiscd/recipe-planner-mern-frontend:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push samiscd/recipe-planner-mern-backend:latest
          docker push samiscd/recipe-planner-mern-frontend:latest

      - name: Create backend-env secret if it doesn't exist
        run: |
          if ! kubectl get secret backend-env &> /dev/null; then
            kubectl create secret generic backend-env \
              --from-literal=PORT=5000 \
              --from-literal=MONGO_URI=mongodb://mongo:27017/recipe-planner \
              --from-literal=JWT_SECRET="temporary_development_secret" \
              --from-literal=CORS_ORIGIN="*"
          else
            echo "Secret backend-env already exists"
          fi

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment-mongo.yaml
          kubectl apply -f service-mongo.yaml
          sleep 10

          kubectl apply -f deployment-backend.yaml
          kubectl apply -f service-backend.yaml
          sleep 10

          kubectl apply -f deployment-frontend.yaml
          kubectl apply -f service-frontend.yaml

          echo "Deployment completed. Frontend available at: $(minikube service recipe-planner-frontend-service --url)"
