name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          & minikube -p minikube docker-env | Invoke-Expression
        shell: powershell

      # Build and push backend image
      - name: Build Backend Docker image
        run: |
          cd app/backend
          docker build -t samiscd/recipe-planner-mern-backend:latest .
        shell: powershell

      - name: Build Frontend Docker image
        run: |
          cd app/frontend
          docker build -t samiscd/recipe-planner-mern-frontend:latest .
        shell: powershell

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Split push operations into separate steps to ensure completion
      - name: Push Backend Docker image
        run: |
          echo "Pushing backend image to Docker Hub..."
          docker push samiscd/recipe-planner-mern-backend:latest
          echo "Backend image push completed."
        shell: powershell

      - name: Push Frontend Docker image
        run: |
          echo "Pushing frontend image to Docker Hub..."
          docker push samiscd/recipe-planner-mern-frontend:latest
          echo "Frontend image push completed."
        shell: powershell

      # Verify images exist in Docker Hub before proceeding
      - name: Verify Docker images are available
        run: |
          echo "Verifying backend image..."
          docker manifest inspect samiscd/recipe-planner-mern-backend:latest

          echo "Verifying frontend image..."
          docker manifest inspect samiscd/recipe-planner-mern-frontend:latest

          echo "Both images verified. Proceeding with deployment."
        shell: powershell

      - name: Create namespace if it doesn't exist
        run: |
          kubectl create namespace food-planner --dry-run=client -o yaml | kubectl apply -f -
        shell: powershell

      - name: Create backend-env secret if it doesn't exist
        run: |
          $secretExists = kubectl get secret backend-env -n food-planner --ignore-not-found
          if (-not $secretExists) {
            echo "Creating backend-env secret..."
            kubectl create secret generic backend-env -n food-planner `
              --from-literal=PORT=5000 `
              --from-literal=MONGO_URI="mongodb://mongo:27017/recipe-planner" `
              --from-literal=JWT_SECRET="temporary_development_secret" `
              --from-literal=CORS_ORIGIN="*"
            echo "Secret backend-env created"
          } else {
            echo "Secret backend-env already exists"
          }
        shell: powershell

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment-mongo.yaml -n food-planner
          kubectl apply -f service-mongo.yaml -n food-planner
          echo "Waiting for MongoDB pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=mongo -n food-planner --timeout=60s

          kubectl apply -f deployment-backend.yaml -n food-planner
          kubectl apply -f service-backend.yaml -n food-planner
          echo "Waiting for backend pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=recipe-planner-backend -n food-planner --timeout=60s

          kubectl apply -f deployment-frontend.yaml -n food-planner
          kubectl apply -f service-frontend.yaml -n food-planner
          echo "Waiting for frontend pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=recipe-planner-frontend -n food-planner --timeout=60s

          echo "Deployment completed."
          echo "Checking pod status:"
          kubectl get pods -n food-planner

          echo "Checking services:"
          kubectl get services -n food-planner

          # Get minikube IP and ensure it's properly formatted
          $minikubeIp = (minikube ip).Trim()
          echo "Minikube IP: $minikubeIp"

          echo "-----------------------------------------------"
          echo "IMPORTANT: On Windows with Docker driver, direct access via NodePort might not work."
          echo "To access your application, use one of these methods:"
          echo ""
          echo "1. For local access: minikube service recipe-planner-frontend-service -n food-planner"
          echo "   This will automatically set up port forwarding and open your browser."
          echo ""
          echo "2. For tunnel access, open a separate terminal and run:"
          echo "   minikube tunnel"
          echo "   Then access: http://localhost:30008"
          echo "-----------------------------------------------"
        shell: powershell
